services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - POSTGRES_URL=postgres://app:app@postgres:5432/app
      - MYSQL_URL=mysql://root:root@mysql:3306/app?connectionLimit=10
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mysql
    # Add volume mapping for faster development
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    #   - /app/.next

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  pgdata:
  mysqldata:
